---
- name: Cisco DNAC Playbook to Create and Deploy CLI Templates
  hosts: localhost
  gather_facts: no
  vars:
    dnac_host: "<your_dnac_host>"
    dnac_username: "<your_dnac_username>"
    dnac_password: "<your_dnac_password>"
    dnac_verify: true
    dnac_port: 443
    dnac_version: "2.3.5.3"
    dnac_debug: false
    project_name: "<your_project_name>"
    template_name: "<your_template_name>"
    template_content: "<your_cli_template_content>"

  tasks:
    - name: Gather Interface Data
      # Replace this with your actual task to gather interface data
      # This should set 'interface_info'

    - name: Filter Interfaces and Create Switch-Port Mapping
      set_fact:
        switch_port_map: "{{ switch_port_map | default({}) | combine({ item.deviceId: new_ports }) }}"
      loop: "{{ interface_info.results | json_query('[].dnac_response.response[]') }}"
      vars:
        current_ports: "{{ switch_port_map[item.deviceId] | default([]) }}"
        new_ports: "{{ current_ports + [item.portName] }}"
      when: 
        - item.deviceId is defined
        - item.portName is defined
        - item.interfaceType == 'Physical'
        - item.status == 'down'
        - "'ATM' in item.description"
        - "'I' in item.description"
        - (item.portName not in current_ports)

    - name: Create CLI Template
      cisco.dnac.configuration_template_create:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        author: "Ansible User"
        description: "CLI template for port configuration"
        name: "{{ template_name }}"
        projectName: "{{ project_name }}"
        templateContent: "{{ template_content }}"
        deviceTypes:
          - productFamily: "Switches and Hubs"
      register: template_creation_result

    - name: Deploy CLI Template to Each Switch
      cisco.dnac.configuration_template_deploy_v2:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        forcePushTemplate: true
        templateId: "{{ template_creation_result.dnac_response.id }}"
        targetInfo:
          - id: "{{ item.key }}"
            type: "MANAGED_DEVICE_UUID"
            params:
              # Add the necessary parameters for template deployment
        loop: "{{ switch_port_map | dict2items }}"
        loop_control:
          loop_var: item
