---
- name: Manage interfaces on Cisco DNAC managed devices
  hosts: all
  gather_facts: no
  vars:
    dnac_host: "your_dnac_host"  # Replace with your Cisco DNAC host
    dnac_username: "your_dnac_username"  # Replace with your Cisco DNAC username
    dnac_password: "your_dnac_password"  # Replace with your Cisco DNAC password
    dnac_verify: true  # Set to false if you want to ignore SSL certificate verification
    dnac_port: 443  # Default port for Cisco DNAC
    dnac_version: "2.3.5.3"  # Cisco DNAC version
    single_switch: "{{ single_switch_var | default('') }}"
    port_state: "{{ port_state_var | default('down') }}"
    specific_ports: "{{ specific_ports_var | default('') }}"
    cat9k_series:
      - "Cisco Catalyst 9300"
      - "Cisco Catalyst 9400"
      - "Cisco Catalyst 9500"

  tasks:
    # Task to obtain device details from DNAC
    - name: Get all device details from DNAC
      cisco.dnac.device_details_info:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: false  # Set to true to enable debug mode
      register: all_devices
      ignore_errors: yes

    # Handling errors during device information retrieval
    - name: Check for errors in getting device details
      fail:
        msg: "Failed to get device details from DNAC"
      when: all_devices is failed

    # Filtering devices that belong to the specified Catalyst series
    - name: Filter devices based on the Catalyst 9k series
      set_fact:
        cat9k_devices: "{{ all_devices.dnac_response | selectattr('series', 'in', cat9k_series) | list }}"
      when: all_devices is succeeded

    # Print the list of filtered devices
    - name: Print the list of Catalyst 9k series devices
      debug:
        msg: "The following are the Catalyst 9k series devices: {{ cat9k_devices | map(attribute='hostname') | list }}"
      when: cat9k_devices is defined

    # Proceed with interface management tasks...
    # ... [Additional tasks to manage ports for each device based on `deviceId`]

  # Additional playbook content can go here
